import { EventEmitter, OnInit, InjectionToken } from '@angular/core';
import { Item } from '../../models/item';
import { LightboxConfigurationService } from '../../services/lightbox-configuration.service';
import { ThumbnailsVisibilityAnimator } from '../../models/thumbnails/animations/thumbnails-visibility-animator';
import { ThumbnailsSliceAnimator } from '../../models/thumbnails/animations/thumbnails-slice-animator';
export declare const WINDOW: InjectionToken<{}>;
export declare function _window(): Window;
export declare class LightboxThumbnailsComponent implements OnInit {
    private readonly _lightboxConfigurationService;
    readonly _win: any;
    items: Item[];
    selectEvent: EventEmitter<{}>;
    thumbnailsVisibilityAnimator: ThumbnailsVisibilityAnimator;
    thumbnailsSliceAnimator: ThumbnailsSliceAnimator;
    activeItem: Item;
    thumbnailsWidth: string;
    thumbnailsHeight: string;
    thickness: number;
    private _thumnailsContainerRef;
    private _thumnailsListRef;
    private _thumnailsRef;
    private _state;
    constructor(_lightboxConfigurationService: LightboxConfigurationService, _win: any);
    ngOnInit(): void;
    readonly direction: 'vertical' | 'horizontal';
    readonly config: LightboxConfigurationService;
    open(): void;
    close(): void;
    toggle(): void;
    resize(): void;
    onTap(item: Item): void;
    selectItem(item: Item): void;
    onWheel(event: any): void;
    onSwipe(event: any): void;
    getItemSrc(item: Item): string;
    checkDirection(): void;
    checkThumbnailsDimensions(): void;
    private _refreshThickness();
    private _animateSlice(item, duration);
    private _getTop(value);
    private _getLeft(value);
}
